[project]
site_name = "Typed dYdX"
site_description = "Typed async client for dYdX indexer, chain, and node workflows."
repo_name = "dydx"
repo_url = "https://github.com/tribulnation/dydx"
copyright = """
Copyright &copy; 2026 Tribulnation
"""
nav = [
  { "Intro" = "index.md" },
  { "Wallet Setup" = "api-keys.md" },
  { "How To" = [
    { "Overview" = "how-to/index.md" },
    "how-to/fetch-market-data.md",
    "how-to/manage-account-data.md",
    "how-to/query-chain-state.md",
    "how-to/inspect-blocks-and-transactions.md",
    "how-to/place-and-manage-orders.md",
    "how-to/paginate-through-results.md",
    "how-to/listen-to-streams.md",
  ] },
  { "Reference" = [
    { "Overview" = "reference/index.md" },
    "reference/error-handling.md",
    "reference/env-vars.md",
    { "API" = [
      { "Overview" = "reference/api/index.md" },
      { "Indexer" = [
        { "Overview" = "reference/api/indexer/index.md" },
        "reference/api/indexer/data.md",
        "reference/api/indexer/streams.md",
      ] },
      { "Chain" = [
        { "Overview" = "reference/api/chain/index.md" },
        "reference/api/chain/modules.md",
        "reference/api/chain/comet.md",
      ] },
      { "Node" = [
        { "Overview" = "reference/api/node/index.md" },
        "reference/api/node/orders.md",
        "reference/api/node/tx.md",
        "reference/api/node/wallet.md",
      ] },
    ] },
  ] },
]

[project.theme]
language = "en"
logo = "media/logo.png"
favicon = "media/logo.png"
features = [
  "content.code.copy",
]

[[project.theme.palette]]
scheme = "slate"
primary = "black"
accent = "amber"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
scheme = "default"
primary = "black"
accent = "amber"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.extra]
homepage = "https://tribulnation.com"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true

[project.markdown_extensions.pymdownx.superfences]

[project.plugins.mkdocstrings.handlers.python]
paths = ["pkg/src"]
inventories = ["https://docs.python.org/3/objects.inv"]
